CREATE DATABASE Olist_DB;
USE Olist_DB;
select * from customers;
select * from orders;
select * from items;
select * from products;
select * from payments;
select * from reviews;
select * from sellers;
select * from geolocation;
select * from product_category_name;

SHOW TABLES;

DESC customers;
DESC orders;
DESC products;
DESC payments;
DESC reviews;
DESC sellers;
DESC geolocation;
DESC product_category_name;



-- 1. Display all customer records.
Select * from  customers;

-- 2. Find all unique customer cities.
Select DISTINCT customer_city from customers;

-- 3. Count the total number of customers.
Select COUNT(*) as Total_Customers from customers;

-- 4. Display all delivered orders.
Select order_id,order_status  From orders WHERE order_status="delivered";

-- 5. Count the number of orders by order status
Select  order_status, COUNT(*) as Total_orders from orders group by order_status;

-- 6. Find the top 10 highest payment values.
select  * from payments; 

Select order_id, payment_value from payments order by payment_value DESC LIMIT 10 ;

-- 7. Calculate the total sales (revenue).
select * from payments;
select Round(sum(payment_value),2)  as Total_sales from payments;

-- 8.Find the average payment value.
select Round(avg(payment_value),2)  as Average_payment from payments;

-- 9.Find the highest payment value.
select max(payment_value) as Maximun_payments from payments;

-- 10. Find the lowest payment value.
select min(payment_value) as Minimun_payments from payments;

-- 11.Display customer details along with their order information.
select * from customers;
select * from orders;

select o.customer_id,c.customer_unique_id, c.customer_city,c.customer_state,o.order_status from customers c
 inner join orders  o on c.customer_id = o.customer_id;

-- 12.Display order details along with payment information.
select * from orders;
select  * from payments; 

select o.order_id ,o.order_status,p.payment_type , p.payment_value from orders o join payments p 
on o.order_id = p.order_id ;


-- 13.Display product details for each order item.
select * from items;
select  * from products;

Select  i.order_id, i.product_id, p.product_category_name
from items i
join products p on i.product_id = p.product_id;
 
-- 14.Display seller details for each order.
select * from sellers;
select * from orders;

select i.order_id ,s.seller_city  from items  i
   join sellers s on i.seller_id = s.seller_id;

-- 15.Display order details along with customer review scores.
select * from orders;
select * from reviews;

select r.review_score, o.order_id, o.order_status from orders o 
join reviews r on r.order_id = o.order_id;

-- 16.Find the total number of orders placed from each customer city.
select * from customers;
select * from orders;

Select  c.customer_city, Count(order_id) as Total_orders from orders o 
join customers c 
on o. customer_id= c.customer_id
group by c.customer_city
order by Total_Orders DESC;


-- 17.Calculate the total revenue generated by each payment type.
select * from payments;
select * from orders;

select  payment_type , sum(payment_value) as Revenue from payments 
group by payment_type;


-- 18.Count the number of reviews for each review score.
select * from reviews;

select  review_score , count(*) as Reviews from reviews group by review_score;   

-- 19.Count the number of sellers in each state.
select * from sellers;

select seller_state , count(*) as No_of_Sellers from sellers 
group by seller_state;


-- 20.Count the total number of products in each product category.
select * from products;

select product_category_name , count(*) as Total_Products from products 
 group by product_category_name 
 order by Total_Products DESC;
 
 

-- 21.Find customer cities having more than 100 customers.
select * from customers;

select customer_city , count(*) as Total_customers from customers 
group by customer_city having Total_customers >100;


-- --22. Find payment types that generated more than ₹10,00,000 in revenue.
select * from payments;
select payment_type,sum(payment_value) as Revenue  from payments group by payment_type
having Revenue > 10000; 



-- 23.Find all orders whose payment value is greater than the average payment value.
select * from payments;
select  order_id , payment_value from payments where payment_value 
> ( select avg(payment_value) from payments);


-- 24.Categorize each payment as High, Medium, or Low based on the payment value.
select * from payments;

select order_id , payment_value ,
CASE 
    When payment_value >=500 then 'High'
    When payment_value >=200  then'Medium'
    else 'low'
end as Payment_category
from payments;    
    
    

-- 25.Rank all orders based on payment value.
select * from payments;
select order_id , payment_value ,
RANK() OVER  (order by payment_value) as Rank_Payments from payments  ; 



-- 26.Assign a Dense Rank to orders based on payment value.
select order_id , payment_value , 
DENSE_RANK() OVER (ORDER BY payment_value ) as Dense_Payment from payments;



-- 27.Assign a Row Number to all orders based on payment value.
select order_id , payment_value , 
ROW_NUMBER() OVER (ORDER BY payment_value ) as Row_Payment from payments;


-- 28.Calculate the running total of payment values.
select order_id , payment_value , 
SUM(payment_value) OVER (order by payment_value ) as Running_Total from payments;


-- 29.Find all orders with payment values greater than 500 using a Common Table Expression (CTE).
select * from payments;

WITH HighestPayment as 
(
select order_id , payment_value from payments where payment_value > 500
)
select * from HighestPayment;



-- 30.Find the top 10 customer cities based on total revenue generated.
select * from customers;
select * from orders;

SELECT
    c.customer_city,
    ROUND(SUM(p.payment_value), 2) AS Total_Revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN payments p
    ON o.order_id = p.order_id
GROUP BY c.customer_city
ORDER BY Total_Revenue DESC
LIMIT 10;













